### ISSUE TITLE
twitter embed stop working on v3

### ISSUE THREAD

**Issue by budikhafiKLY** [oscarotero/Embed#421] opened 2020-12-18 03:53 UTC
Recently Twitter has started returning 400 server error on Embed v3:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Ftwitter.com%2Fdrupalassoc%2Fstatus%2F1217450156523692038

Whereas it still working as expected on v4:
https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Ftwitter.com%2Fdrupalassoc%2Fstatus%2F1217450156523692038

Any idea on what could have changed (either on Twitter side or on how Embed does thing differently in v4) so I can start digging in the right direction?

Much appreciated, and thanks for this awesome library!

**Comment by tanakahisateru** [comment] 2020-12-18 16:30
`\Embed\Http\CurlDispatcher::dispatch`

```php
        //Some sites returns 403 with the default user-agent
        if ($response->getStatusCode() === 403) {
            $options[CURLOPT_USERAGENT] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36';

            return $this->exec($url, $options);
        }
```

I found retrying code using alternative  User-Agent text when 403 returned, but Twitter now returns 400 instead.

**Comment by tanakahisateru** [comment] 2020-12-18 16:39
HTTP client of
- embed v3 is Curl -> default UA: `curl/<version>`
- embed v4 is Guzzle -> default UA: `Guzzle/<Guzzle_Version> curl/<curl_version> PHP/<PHP_VERSION>`

This is why Twitter rejects only embed v3, I guess 🤔

**Comment by tanakahisateru** [comment] 2020-12-18 16:44
@budikhafiKLY Can you try below workaround idea?

```php
$dispatcher = new CurlDispatcher([
    CURLOPT_USERAGENT => 'My browser is not evil.',
]);
```

**Comment by RiverVanRain** [comment] 2020-12-18 23:24
@tanakahisateru This works for me very well:

```
$dispatcher = new CurlDispatcher([
    CURLOPT_USERAGENT => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://google.com/bot.html)',
]);
```

**Comment by amjad-emfzlcc** [comment] 2020-12-21 20:15
Still not working for me

**Comment by budikhafiKLY** [comment] 2020-12-22 00:29
> @budikhafiKLY Can you try below workaround idea?
> 
> ```
> $dispatcher = new CurlDispatcher([
>     CURLOPT_USERAGENT => 'My browser is not evil.',
> ]);
> ```

yes, this works for me
thanks

**Comment by RiverVanRain** [comment] 2020-12-22 17:24
> Still not working for me
Confirmed :(

**Comment by amjad-emfzlcc** [comment] 2020-12-22 17:26
> > Still not working for me
> 
> Confirmed :(

working for me now

**Comment by amjad-emfzlcc** [comment] 2020-12-22 17:29
```
<?php
class CustomCurlDispatcher extends \Embed\Http\CurlDispatcher
{
    public function __construct(array $config = [])
    {
        $config = [CURLOPT_USERAGENT => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://google.com/bot.html)'];

        parent::__construct($config);
    }
}
$dispatcher = new CustomCurlDispatcher();
$embed = Embed::create($url, $config, $dispatcher);
```

**Comment by RiverVanRain** [comment] 2020-12-22 18:40
```
$desktop_agents = [
			'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
            'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14',
            'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36',
            'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
            'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
			'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36',
            'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'
		];
		
		$user_agent = array_rand($desktop_agents, 2);

		$config = [
			CURLOPT_USERAGENT => $desktop_agents[$user_agent[0]],
		];
```

;)

**Comment by oscarotero** [comment] 2020-12-24 09:45
v3.4.13 released including a fix for this.

**Closed by oscarotero** 2020-12-24 09:45 UTC
