### ISSUE TITLE
Instagram embed returning login

### ISSUE THREAD

**Issue by amjad-eremnews** [oscarotero/Embed#359] opened 2020-05-27 12:49 UTC
Instagram is returning login content on production server, while on local embeds is working fine.

**Comment by amjad-eremnews** [comment] 2020-05-27 12:50
library version version is 3.x

**Comment by oscarotero** [comment] 2020-05-27 13:44
Yes, this is a duplicate of https://github.com/oscarotero/Embed/issues/357. 
It's a change from instagram, and I'm thinking in the best way to solve it.

**Comment by oscarotero** [comment] 2020-05-30 22:31
Released a workaround in 3.4.5

**Closed by oscarotero** 2020-05-30 22:31 UTC

**Comment by amjad-eremnews** [comment] 2020-05-31 12:47
Awesome, it is fixed. verified!
Many thanks
